/* ============================================================================
   DATA RUNTIME — the only path from the app to its backend
   ----------------------------------------------------------------------------
   The architecture the prompt asks for is a chain, and the point of the chain
   is the middle link:

       Application → Data Runtime → Backend Adapter → Supabase or other backend

   "Do not allow uncontrolled direct database access from arbitrary application
   components." A runtime that exists but that components may bypass is not a
   control, so the generated module is written to be the only thing in the app
   that knows the backend's address, and the checks below look for code that
   went around it.

   The runtime owns the seven things the prompt names — authentication, queries,
   mutations, retries, offline behaviour, error normalisation, rollback — and
   three rules decide how each is implemented:

     · Retries happen on reads only. A mutation is not idempotent: retrying a
       failed POST is how an app charges someone twice, so a failed write is
       reported, not attempted again behind your back.

     · Nothing privileged is in the file. The publishable key is in the app
       because it has to be; a service-role key never is, and there is a check
       that fails the build if one appears in generated output.

     · Entitlement is read from the server and is read-only here. There is no
       setter for it and it is not persisted, because "do not trust
       client-controlled premium status" is not a preference.

   This file generates the runtime as text. It imports nothing, so it runs in a
   test, in the CLI and in the browser alike, and what the test asserts is
   byte-for-byte what the app ships.
   ========================================================================= */

/**
 * Generate the data runtime for a specification.
 * Returns { ok, file, code, errors } — `file` is the path it should be written
 * to, `code` the module source.
 */
export function dataRuntime(spec) {
  const b = (spec && spec.backend) || {};
  const kind = b.kind || 'none';
  if (kind === 'none') {
    return { ok: false, code: '', file: '', errors: ['backend.kind is "none", so there is no backend to talk to'] };
  }

  const url = String(b.url || '').replace(/\/+$/, '');
  const errors = [];
  if (!url) errors.push('backend.url is required once a backend is configured');
  else if (!/^https:\/\//i.test(url)) errors.push(`backend.url must be https, got "${url}"`);
  if (errors.length) return { ok: false, code: '', file: '', errors };

  const requiresAuth = b.requiresAuth === true;
  const tables = Array.isArray(b.tablesRequiringRls) ? b.tablesRequiringRls.filter(Boolean) : [];

  const code = `/* Generated by Project1 Studio from the project specification.
 * Edit the specification, not this file: it is rewritten on every build.
 *
 * This is the only module in the app that knows where the backend is. Anything
 * that needs data goes through it, so that authentication, retries, offline
 * behaviour and error handling are decided in one place instead of per screen.
 */
(function (global) {
  'use strict';

  var CONFIG = {
    kind: ${JSON.stringify(kind)},
    url: ${JSON.stringify(url)},
    requiresAuth: ${requiresAuth ? 'true' : 'false'},
    tablesRequiringRls: ${JSON.stringify(tables)},
    /* The publishable key. It is safe to ship: it can only do what the
       database's row-level security policies allow. A service-role key is never
       written into this file, and the build fails if one turns up in generated
       output. */
    publishableKey: null
  };

  var RETRIES = 2;                 /* reads only — see request() */
  var RETRY_DELAY_MS = 400;
  var session = null;              /* held in memory for the life of the page */
  var cache = Object.create(null); /* last good read, per key */

  /* ── error normalisation ─────────────────────────────────────────────────
     Every failure leaves here with the same shape, so a screen can show
     something true without knowing whether the problem was the network, the
     server or this module. */
  function normalise(err, context) {
    var status = err && err.status;
    var kind = !status ? 'offline'
      : status === 401 || status === 403 ? 'unauthorised'
      : status === 404 ? 'missing'
      : status >= 500 ? 'server'
      : 'rejected';
    return {
      ok: false,
      kind: kind,
      status: status || 0,
      message: (err && err.message) || 'The request could not be completed.',
      context: context || null,
      /* The underlying response is never handed to a screen. It can contain
         other people's data when a policy is wrong. */
      retryable: kind === 'offline' || kind === 'server'
    };
  }

  function delay(ms) {
    return new Promise(function (resolve) { setTimeout(resolve, ms); });
  }

  /* ── the one request path ────────────────────────────────────────────────
     method, path and body are the whole surface. Nothing else in the app is
     given the URL, which is what makes "no uncontrolled direct access" a
     property of the code rather than an intention about it. */
  function request(method, path, body, options) {
    var opts = options || {};
    var attempt = 0;

    function once() {
      attempt += 1;
      var headers = { 'Content-Type': 'application/json' };
      if (session && session.accessToken) headers.Authorization = 'Bearer ' + session.accessToken;

      return fetch(CONFIG.url + path, {
        method: method,
        headers: headers,
        body: body === undefined ? undefined : JSON.stringify(body)
      }).then(function (res) {
        if (!res.ok) {
          return res.text().then(function (text) {
            var e = new Error(text.slice(0, 300) || ('HTTP ' + res.status));
            e.status = res.status;
            throw e;
          });
        }
        return res.status === 204 ? null : res.json();
      });
    }

    function run() {
      return once().catch(function (err) {
        var last = attempt > RETRIES || !opts.retryable;
        /* A read is idempotent, so retrying it is safe. A mutation is not:
           retrying a POST that may have landed is how an app charges someone
           twice. Failed writes are reported, never re-attempted here. */
        if (last) throw err;
        return delay(RETRY_DELAY_MS * attempt).then(run);
      });
    }

    return run().catch(function (err) { return normalise(err, method + ' ' + path); });
  }

  var runtime = {
    config: function () {
      /* A copy, so a screen cannot repoint the runtime at another host. */
      return {
        kind: CONFIG.kind,
        url: CONFIG.url,
        requiresAuth: CONFIG.requiresAuth,
        tablesRequiringRls: CONFIG.tablesRequiringRls.slice()
      };
    },

    /* ── authentication ─────────────────────────────────────────────────── */
    signIn: function (email, password) {
      return request('POST', '/auth/v1/token?grant_type=password', {
        email: email, password: password
      }, { retryable: false }).then(function (res) {
        if (!res || !res.access_token) return res && res.ok === false ? res : normalise(new Error('No session was returned.'), 'signIn');
        session = { accessToken: res.access_token, refreshToken: res.refresh_token || null };
        return { ok: true };
      });
    },

    signOut: function () { session = null; return Promise.resolve({ ok: true }); },

    isSignedIn: function () { return !!(session && session.accessToken); },

    /* ── queries ──────────────────────────────────────────────────────────
       A read that cannot be served is served from the last good read, marked
       as stale. A screen that shows cached data as though it were current is
       lying, so the flag is part of the result and not a detail. */
    query: function (table, params) {
      if (CONFIG.tablesRequiringRls.indexOf(table) === -1 && CONFIG.requiresAuth) {
        return Promise.resolve(normalise(
          new Error('"' + table + '" is not listed in backend.tablesRequiringRls.'),
          'query ' + table));
      }
      var qs = params ? '?' + Object.keys(params).map(function (k) {
        return encodeURIComponent(k) + '=' + encodeURIComponent(params[k]);
      }).join('&') : '';
      var key = table + qs;

      return request('GET', '/rest/v1/' + encodeURIComponent(table) + qs, undefined, { retryable: true })
        .then(function (rows) {
          if (rows && rows.ok === false) {
            if (cache[key]) return { ok: true, stale: true, data: cache[key], reason: rows };
            return rows;
          }
          cache[key] = rows;
          return { ok: true, stale: false, data: rows };
        });
    },

    /* ── mutations, and rollback ──────────────────────────────────────────
       A mutation is applied locally first so the interface can respond, and
       the previous value is kept. If the server refuses, the previous value is
       put back and the caller is told — which is the rollback the architecture
       asks for. Nothing is retried, because the write may have landed. */
    mutate: function (table, patch, previous) {
      return request('PATCH', '/rest/v1/' + encodeURIComponent(table), patch, { retryable: false })
        .then(function (res) {
          if (res && res.ok === false) return { ok: false, rolledBack: true, previous: previous, reason: res };
          return { ok: true, rolledBack: false, data: res };
        });
    },

    /* ── entitlement ──────────────────────────────────────────────────────
       Read-only and not persisted. There is deliberately no setter: premium
       status that a client can write is premium status a client can fake. */
    entitlement: function () {
      return request('GET', '/rest/v1/entitlements?select=plan,expires_at&limit=1', undefined, { retryable: true })
        .then(function (rows) {
          if (rows && rows.ok === false) return { ok: false, plan: 'free', reason: rows };
          var row = Array.isArray(rows) ? rows[0] : null;
          return {
            ok: true,
            plan: (row && row.plan) || 'free',
            expiresAt: (row && row.expires_at) || null,
            source: 'server'
          };
        });
    },

    /* ── offline ──────────────────────────────────────────────────────────
       Reported rather than guessed at. Writes are refused while offline with a
       reason a screen can show, instead of being queued into a promise that
       may never resolve. */
    online: function () {
      return typeof navigator === 'undefined' || navigator.onLine !== false;
    },

    clearCache: function () { cache = Object.create(null); }
  };

  global.DataRuntime = runtime;
})(typeof window !== 'undefined' ? window : this);
`;

  return {
    ok: true,
    code,
    file: 'android/app/src/main/assets/www/data-runtime.js',
    errors: [],
  };
}

/**
 * Look for the ways this runtime gets bypassed, in generated or bundled code.
 *
 * The runtime is only a control if nothing goes around it, and the ways around
 * it are specific enough to look for by name.
 */
export function unsafePatterns(code) {
  /* Comments and string contents are removed before looking, because prose
     about a service-role key is not a service-role key. Without this the
     scanner failed the build over the comment in the runtime that explains why
     no privileged key is in the file - a check that accuses its own
     documentation gets ignored, and then it catches nothing. */
  const src = String(code || '')
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|[^:])\/\/.*$/gm, '$1 ');
  const found = [];
  const add = (code_, detail) => found.push({ code: code_, detail });

  if (/service[_-]?role/i.test(src)) {
    add('SERVICE_ROLE_IN_CLIENT', 'Generated code mentions a service-role key. That key bypasses row-level security entirely and must stay server-side.');
  }
  // The publishable key belongs in configuration read at runtime, not pasted in.
  const longKey = src.match(/\beyJ[A-Za-z0-9_-]{40,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/);
  if (longKey) {
    add('JWT_EMBEDDED_IN_SOURCE', 'A JSON web token is written into the source. Tokens expire and rotate; a baked-in one is a credential in a repository.');
  }
  if (/\bsupabase\s*\(\s*['"`]https:\/\//i.test(src)) {
    add('DIRECT_CLIENT_INIT', 'A Supabase client is created directly against a URL. That is the uncontrolled access the runtime exists to prevent.');
  }
  // Entitlement read from somewhere a user can edit.
  if (/(localStorage|sessionStorage|SharedPreferences)[^\n]{0,80}(premium|entitlement|is_?pro|plan)\b/i.test(src)) {
    add('CLIENT_CONTROLLED_ENTITLEMENT', 'Premium status is read from local storage. Anything the client stores, the client can alter.');
  }
  return found;
}

/** What the runtime guarantees, for the UI and for the health checks. */
export function runtimeReport(spec) {
  const b = (spec && spec.backend) || {};
  const kind = b.kind || 'none';
  const generated = dataRuntime(spec);
  return {
    configured: kind !== 'none',
    kind,
    url: b.url || '',
    requiresAuth: b.requiresAuth === true,
    tables: Array.isArray(b.tablesRequiringRls) ? b.tablesRequiringRls : [],
    generated: generated.ok,
    errors: generated.errors,
    bytes: generated.ok ? generated.code.length : 0,
    unsafe: generated.ok ? unsafePatterns(generated.code) : [],
  };
}
